version: 1.0.{build}
configuration: Release
platform: x64
image: Visual Studio 2019
before_build:
- ps: >-
    git submodule update --init --recursive

    cmake -G "Visual Studio 16 2019 Win64" -DTEST_DIR=c: -DCMAKE_BUILD_TYPE=Release -DVERSION_NAMES=1 .

build:
  verbosity: minimal
  parallel: true

build_script: cmake --build . --target check --config Release

notifications:
- provider: Email
  to:
  - qwart279@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false

branches:
  only:
    - master
